development:
  strategy: oauth
  oauth_consumer_key: 7CdYpMr1ShLddGg57zCgYg
  oauth_consumer_secret: UVWMO2A75Cdn0G1HZB9YPI4rV3cMkgMNK1GiFqvSX4
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/twitter/oauth_callback"
test:
  strategy: oauth
  oauth_consumer_key: 7CdYpMr1ShLddGg57zCgYg
  oauth_consumer_secret: UVWMO2A75Cdn0G1HZB9YPI4rV3cMkgMNK1GiFqvSX4
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
production:
  strategy: oauth
  oauth_consumer_key: prodkey
  oauth_consumer_secret: prodsecret 
  authorize_path: "/oauth/authenticate"
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 14 # days

