#!/usr/bin/env bash

source ~/.bashrc

RAILS_ENV="${RAILS_ENV:-development}"

enter $release_path

info "RVM loading gems..."
bundle install --without test development

info "Running migrations..."
rake db:migrate --trace >> ~/shared/log/migrate.log 2>&1

mkdir -p $release_path/tmp/pids

info "Restarting unicorns..."
bdsm unicorn restart
